services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
    environment:
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_URL=${S3_URL}
      - API_KEY=${API_KEY}
      - PUBLIC_FRONTEND_URL=${PUBLIC_FRONTEND_URL}
    env_file:
      - .env  # This loads all .env variables